### ISSUE TITLE
Cart2 stack not adding to basket

### ISSUE THREAD

**Issue by tiggyh** [yuzoolcode/yuzoolthemes-tracking#27] opened 2019-06-08 15:55 UTC
Hi,
I have recently purchased the Cart2 stack and have included the Cart Base stack at the top of the page as instructed in the documents. However, when I press the 'Add To Basket' button, the box pops up with 'Your Basket is Empty'.

I have the test keys for my stripe account in place but it seems as though it is not generating the basket with the Checkout button for stripe in the first place.

Any help would be greatly appreciated.
Many thanks.

<img width="615" alt="Screenshot 2019-06-08 16 51 10" src="https://user-images.githubusercontent.com/50714088/59149514-b48f2a00-8a0d-11e9-89b4-2487f54568f8.png">

**Comment by yuzoolcode** [comment] 2019-06-09 23:24
Hi @tiggyh  - do you have a link?

It works in testing again today so I'm guessing it must be a theme clash? 
Can you publish to a test domain and share a link and / or let me know other Stacks on the page and the theme?

**Comment by tiggyh** [comment] 2019-06-10 05:53
Hi,
yes here’s a test page:
https://www.gillickcoaching.com/page

And I’m using foundation stacks and the foundation theme.


Sent from my iPhone

On 10 Jun 2019, at 00:24, yuzoolcode <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @tiggyh<https://github.com/tiggyh> - do you have a link?

It works in testing again today so I'm guessing it must be a theme clash?
Can you publish to a test domain and share a link and / or let me know other Stacks on the page and the theme?

**Comment by yuzoolcode** [comment] 2019-06-10 07:16
Just done a test of the demo in Foundation theme and it works fine (adds to basket)

![RapidWeaver 2019-06-10 at 16 15 27](https://user-images.githubusercontent.com/4608547/59178816-14670b80-8b9b-11e9-85ac-539dee3bf653.jpg)

**Comment by yuzoolcode** [comment] 2019-06-10 07:18
- Stripe only is working too
- Can I suggest you try the demo in the Cart2 ZIP download?
- Test that this works in RW for you
- If so then it might be another Stack on your page. To test that, delete one at a time until it works then we know which on either is (work from a duplicate of your project)
- If not, it could be the input credentials in the Cart 2 Stack. And it's worth double checking those are all correct

Let me know

**Comment by tiggyh** [comment] 2019-06-10 16:01
Unfortunately I didn't receive a RW demo in the download zip:

<img width="181" alt="Screenshot 2019-06-10 17 00 39" src="https://user-images.githubusercontent.com/50714088/59208612-52672e00-8ba1-11e9-83c3-014845e853b4.png">

**Comment by tiggyh** [comment] 2019-06-10 16:15
I've removed every other stack aside from the two cart variable stacks and tried it with other themes and it still pops up with Basket empty.
It must be the settings I have in the Enable Cart at the top of the page...  I will compare to the demo if you're able to send it over.
<img width="1191" alt="Screenshot 2019-06-10 17 09 02" src="https://user-images.githubusercontent.com/50714088/59209478-5005d380-8ba3-11e9-87a4-84d73f62802e.png">

**Comment by tiggyh** [comment] 2019-06-10 16:29
I've kept the Enable Cart 2 stack with all the current settings, deleted both the cart variable stacks and added a cart item stack instead. It now works and the basket is getting populated. However, the Check Out button then doesn't do anything or pull up the stripe window.

**Comment by tiggyh** [comment] 2019-06-10 18:11
I've stripped it all the way back to just the Enable Cart2 and the Variable Stack and have been through the options one by one to see what bugs it out. It seems as though as soon as I uncheck 'Show Title' it doesn't update the basket and the basket is empty! Is there any possibility of having the title unchecked?

**Comment by tiggyh** [comment] 2019-06-10 18:11
Still doesn't fix the check out with stripe button not working though.

**Comment by yuzoolcode** [comment] 2019-06-10 20:41
Hmmm - good research!
That said, unchecking the title this side is working:

![CleanShot 2019-06-11 at 05 38 54](https://user-images.githubusercontent.com/4608547/59225323-5891f480-8c0b-11e9-9713-51b5cfbfa3d1.jpg)

I think the best thing to do is swap projects.

Here's the one from the demo site:
https://www.dropbox.com/s/20da9ijz431097o/Cart%202.zip?dl=1
(ignore the missing images)

Can you attach your site?
Cheers

**Comment by tiggyh** [comment] 2019-06-10 21:05
Many thanks for looking at this, sorry it's a weird one. I've checked/unchecked title boxes and it's now adding to basket but the checkout stripe button not throwing put the stripe payment window still. 

[foryuzool.rw8.zip](https://github.com/yuzoolcode/yuzoolthemes-tracking/files/3273797/foryuzool.rw8.zip)

**Comment by tiggyh** [comment] 2019-06-10 21:12
I think it seems the Show Title can be unchecked but the Item Name can't be blank for the basket to work.

**Comment by yuzoolcode** [comment] 2019-06-10 21:30
Yes the Item Name is needed - even if the title is unchecked for the user - that variable is needed to send the item to PayPal or Stripe.

**Comment by yuzoolcode** [comment] 2019-06-10 21:31
But I think the answer is the SKU

Please enable the SKU in the Variable Stack and it should work.

**Comment by tiggyh** [comment] 2019-06-10 21:46
Wonderful, thank you! The button does something but it redirects to the home page and doesn't throw up the stripe checkout window still.

**Comment by yuzoolcode** [comment] 2019-06-11 08:12
Seems to be a bug around the "send additional email". Not sure when can release a fix for that. 

In the meantime the work around is to have this off and have email receipts "on" inside Stripe settings and email notifications. So the customer and seller will be notified of a sale. 

This Stack setting was just a fallback so not super essential at this time as Stripe provides the same information.

**Comment by tiggyh** [comment] 2019-06-11 19:02
No worries, thank you very much for the help. I have it all now working. 

Only trouble I have now is the Clear Cart. I've tested it in your demo and the clear cart isn't in there so the basket still remembers the content after payment. 

I've added the clear cart on my thank you page which it successfully redirects to but then the basket icon at the top of the page completely disappears so I can't double check that it's empty and when I resimulate the page the icon reappears and the content is still in there.

Also, the subtotal doesn't update unless there's a page refresh. Any chance of getting it to update when items are added to the basket? Or have some way of refreshing the page when something gets added to the basket.

Sorry!

**Comment by yuzoolcode** [comment] 2019-06-11 22:58
For the Clear Cart - you need to add it to the bottom of the page.

For the subtotal int cart pop up - every time I click "add to basket" the sub total changes. Is that not working for you?

For the sub total in the Cart Button, yes that only shows on page refresh at the moment.

**Closed** 2019-06-18 05:58 UTC
